# Generated by Django 3.1.1 on 2020-11-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='cash',
            new_name='total',
        ),
    ]
