# Generated by Django 3.1.1 on 2020-12-01 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_auto_20201127_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='total',
            new_name='remain_cash',
        ),
    ]
