# Generated by Django 3.1.1 on 2020-12-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0004_auto_20201201_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='remain_cash',
            field=models.FloatField(),
        ),
    ]
