# Generated by Django 3.1.1 on 2020-12-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0005_auto_20201208_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='remain_cash',
            field=models.FloatField(default='0.0'),
        ),
    ]
